export const mockTables = [
    { id: 1, tableType: 'Mesa', tableNumber: 1 },
    { id: 2, tableType: 'Mesa', tableNumber: 2 },
    { id: 3, tableType: 'Mesa', tableNumber: 3 },
    { id: 4, tableType: 'Mesa', tableNumber: 4 },
    { id: 5, tableType: 'Barra', tableNumber: 1 },
    { id: 6, tableType: 'Barra', tableNumber: 2 },
    { id: 7, tableType: 'Barra', tableNumber: 3 },
    { id: 8, tableType: 'Barra', tableNumber: 4 },
    { id: 9, tableType: 'Terraza', tableNumber: 1 },
    { id: 10, tableType: 'Terraza', tableNumber: 2 },
    { id: 11, tableType: 'Terraza', tableNumber: 3 },
    { id: 12, tableType: 'Terraza', tableNumber: 4 },
    { id: 13, tableType: 'Terraza', tableNumber: 5 },
    { id: 14, tableType: 'Terraza', tableNumber: 6 },
    { id: 15, tableType: 'Terraza', tableNumber: 7 },
    { id: 16, tableType: 'Mesa', tableNumber: 5 },
    { id: 17, tableType: 'Mesa', tableNumber: 6 },
    { id: 18, tableType: 'Mesa', tableNumber: 7 },
    { id: 19, tableType: 'Mesa', tableNumber: 8 },
    { id: 20, tableType: 'Mesa', tableNumber: 9 },
    { id: 21, tableType: 'Mesa', tableNumber: 10 },
    { id: 22, tableType: 'Mesa', tableNumber: 11 },
    { id: 23, tableType: 'Mesa', tableNumber: 12 },
    { id: 24, tableType: 'Mesa', tableNumber: 13 },
    { id: 25, tableType: 'Mesa', tableNumber: 14 },
];

export const mockDishes = [
    { id: 1, name: 'Lomo a la Parrilla' },
    { id: 2, name: 'Ensalada Mediterránea' },
    { id: 3, name: 'Risotto de Champiñones' },
    { id: 4, name: 'Pasta Carbonara' },
    { id: 5, name: 'Salmón al Horno' },
    { id: 6, name: 'Pollo al Curry' },
    { id: 7, name: 'Filete Mignon' },
    { id: 8, name: 'Tacos de Pescado' },
    { id: 9, name: 'Ceviche Peruano' },
    { id: 10, name: 'Sushi Variado' },
];
